name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/.nvmrc') }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run lint -s
      - run: npm run dist -s && mv storybook-static public/storybook
      - run: npm run report:size
      - run: npm run report:package
      - run: npm run test:coverage -s --json --runInBand
      # - run: npm run test:integration -s
      - run: npm run test:performance -s
      - run: base64 < ./tests/integration/__image_snapshots__/__diff_output__/* || true
      - run: mv coverage/lcov-report build || true
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: reports
          path: public
          retention-days: 1
